spring:
  application:
    name: employee-service
  h2:
    console.enabled: true

server.port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

